## **“End-to-End Sales, Profitability & Performance Analysis using MySQL”**

-- database 
CREATE DATABASE awesome; 
-- analyzing all the tables 
select * from sales_data;
select * from sales_persons;
select * from products;
select * from geography;

/*   🟢 LEVEL 1: Basics (SQL Fundamentals)
 These check SELECT, WHERE, ORDER BY, aggregates.  */

-- 1)  Show all sales transactions that happened in 2022.
select * from sales_data
where year(Sale_Date) = 2022;

-- 2) Find the total sales amount and total boxes sold.
select sum(amount) as total_sales_amount,
sum(boxes) as total_boxes_sold
from sales_data;

-- 3) List all unique sales regions.
select distinct region
from geography;

-- 4) Find the top 5 highest sales transactions by amount.
select *
 from sales_data
 order by amount desc
 limit 5;
 
 -- 5) Show sales where boxes sold > 200.
 select *  from sales_data
 where boxes > 200;
 
 -- 6) Find total sales amount per product.
 select product_id,sum(amount) as total_sales_amount
 from sales_data
 group by Product_ID
 order by Product_ID asc;
 
 -- 7) Count how many sales were done by each sales person.
 select Sp_id,count(*) as no_of_sales 
 from sales_data
 group by Sp_id
 order by Sp_id;
 
 -- 8) Display all products belonging to the ‘Bars’ category.
 select product
 from products 
 where category in ('Bars');
 
 -- 9) Find the average sales amount per transaction.
 select round(avg(amount),2) as avg_sale_per_trns
 from sales_data;
 
 -- 10) List sales ordered by date (latest first).
 select *
from sales_data
order by sale_date desc;


#  🟡 LEVEL 2: Intermediate (JOINs & Grouping)

-- 1) Show sales person name, product name, region, amount for every sale.
select s.sales_person as sales_person_name,
p.product,
g.region,
ss.amount
from sales_data ss
join products p
on ss.Product_ID = p.Product_ID
join sales_persons s
on ss.Sp_id = s.SP_ID
join geography g
on ss.Geo_id = g.Geo_id;

-- 2) Find total sales amount per sales person.
select sp_id,
sum(amount) as total_sales_amount
from sales_data
group by Sp_id
order by Sp_id;

-- 3) Calculate total boxes sold per region.
select  g.region,
sum(ss.boxes) as total_boxes
from sales_data ss
join geography g
on ss.Geo_id = g.Geo_id
group by g.Region;

-- 4) Find total revenue generated by each product category.
select p.category,
sum(ss.amount) as total_revenue
from sales_data ss
join products p
on ss.Product_id = p.Product_ID
group by p.Category;

-- 5) Show team-wise total sales (Yummies vs Delish).
select s.team,
sum(amount)as total_sales
from sales_data ss
join sales_persons s
where Team in('Yummies','Delish')
group by s.Team;

-- 6) Identify top 3 sales persons by total revenue.
select s.sales_person,
       sum(ss.amount) as total_revenue
from sales_data ss
join sales_persons s
  on ss.sp_id = s.sp_id
group by s.sales_person
order by total_revenue desc
limit 3;


-- 7) Find monthly sales trend (year–month wise).
select
date_format(date,'%Y-%m') as months,
sum(amount) as sales
from sales_data
group by date_format(date,'%Y-%m')
order by months;

-- 8) Show country-wise total sales.
select g.geo as country,
sum(s.amount) as total_sales
 from sales_data s
 join geography g
on s.Geo_id= g.Geo_id
group by country;

-- 9) Find products that never had any sales.
select p.product_id
from products p
left join sales_data s
  on p.product_id = s.product_id
where s.product_id is null;

-- 10) List sales persons who never made a sale.

select s.sp_id
from sales_persons s
left join sales_data sd
  on s.sp_id = sd.sp_id
where sd.sp_id is null;

-- 11) Find all products that have never been sold, along with their category.

select p.product,p.category
from products p
left join  sales_data s 
on s.product_id = p.product_id
where s.Product_id is null
group by p.Product_id,p.product,p.category;

-- 12)Find the top 3 sales persons by total revenue, and show their total revenue.
select sp.sales_person,sum(s.amount) as total_revenue
from sales_persons sp
join sales_data s
on s.sp_id = sp.sp_id
group by sp.Sales_Person
order by sum(amount) desc
limit 3;

/* 13) For each sales team, calculate total revenue,
  number of transactions, and average deal size.  */
  select sp.Team,
  sum(sd.amount) as total_revenue,
  count(amount) as total_no_of_trns,
   (sum(sd.amount) / count(amount)) as avg_deal_size
  from sales_persons sp
  join sales_data sd
  on sp.sp_id = sd.sp_id
  group by sp.Team;
  
  
# 🟠 LEVEL 3: Advanced (Business Thinking SQL)

-- 1) Calculate profit per transaction
select s.Sp_id,s.Product_ID,s.Sale_Date,
(s.amount - (s.Boxes * p.cost_per_box)) as profit_per_trns
from sales_data s
join products p
on s.Product_id = p.Product_ID;

-- 2) Find top 5 most profitable products.
select p.Product,
sum(s.amount - (s.Boxes * p.cost_per_box)) as profits
from sales_data s
join products p
on s.Product_id = p.Product_ID
group by p.Product_ID, p.Product 
order by profits desc
limit 5;

-- 3) Identify sales persons with highest average deal size.

select 
 sp.sales_person,
(sum(sd.amount) / count(*)) as avg_deal_size
from sales_persons sp
join sales_data sd
on sp.SP_ID = sd.Sp_id
group by sp.sales_person,sd.Amount
order by avg_deal_size desc;

-- 4) Find region-wise profit margin.
/* Profit ≠ Profit Margin
Profit = Revenue − Cost
Profit Margin = Profit / Revenue
*/
select g.region,
round(
  sum(s.amount - (s.boxes * p.cost_per_box)) 
  / sum(s.amount) * 100
, 2) as profit_margin_pct 
from sales_data s
join products p
on s.Product_id = p.Product_ID
join geography g
on g.Geo_id = s.Geo_id
group by g.Region
order by profit_margin_pct desc;

-- 5) Show team contribution % to total company revenue.
with team_revenue as (
  select sp.team,
         sum(sd.amount) as team_revenue
  from sales_persons sp
  join sales_data sd
    on sp.sp_id = sd.sp_id
  group by sp.team
),
company_revenue as (
  select sum(amount) as total_revenue
  from sales_data
)
select t.team,
       t.team_revenue,
       round(t.team_revenue / c.total_revenue * 100, 2) as contribution_pct
from team_revenue t
cross join company_revenue c
order by contribution_pct desc;


-- 6) Rank sales persons within each team by total sales.

select sp.sp_id,
sp.sales_person,
sp.Team,
sum(amount) as total_sales,
row_number()over(partition by sp.team order by sum(amount) desc) as ranks
from sales_persons sp
join sales_data sd 
on sp.SP_ID = sd.Sp_id
group by sp.sp_id,
sp.sales_person,
sp.Team;

-- 7) Find best-selling product per region.
with best_selling_products as ( 
select 
p.product_id,
p.product,
g.region,
sum(sd.amount) as total_sales,
row_number()over(partition by g.region order by sum(sd.amount) desc) as rn
from products p
join sales_data sd
on p.Product_ID = sd.Product_id
join geography g
on g.Geo_id = sd.Geo_id
group by p.product_id,
p.product,
g.region
)
select *
 from best_selling_products
  where rn = 1;


-- 8) Detect low-performing products (bottom 20% by revenue).
with product_revenue as (
  select p.product_id,
         p.product,
         sum(sd.amount) as total_sales
  from products p
  join sales_data sd
    on p.product_id = sd.product_id
  group by p.product_id, p.product
),
ranked as (
  select *,
         ntile(5) over (order by total_sales) as bucket
  from product_revenue
)
select product_id, product, total_sales
from ranked
where bucket = 1;


-- 9) Identify sales persons whose performance is below team average.
with person_sales as (
  select sp.sp_id,
         sp.sales_person,
         sp.team,
         sum(sd.amount) as person_revenue
  from sales_persons sp
  join sales_data sd
    on sp.sp_id = sd.sp_id
  group by sp.sp_id, sp.sales_person, sp.team
),
team_avg as (
  select team,
         avg(person_revenue) as team_avg_revenue
  from person_sales
  group by team
)
select p.sp_id,
       p.sales_person,
       p.person_revenue,
       t.team_avg_revenue
from person_sales p
join team_avg t
  on p.team = t.team
where p.person_revenue < t.team_avg_revenue;


-- 10) Find month-over-month sales growth %.
with monthly_sales as (
select 
date_format(sale_date,'%Y-%m') as month,
sum(amount) as total_sales
from sales_data
group by date_format(sale_date,'%Y-%m')
order by month
)
, previous_month_sales as (
select month,
total_sales,
lag(total_sales) over(order by month) as previous_sales
from monthly_sales
)
select *,
round((total_sales - previous_sales) / previous_sales*100,2) as mom_pct
from previous_month_sales;


-- # 🔴 LEVEL 4: Expert
/*  1) Create a sales performance segmentation:
High performers
Medium performers
Low performers
*/
 with sales as(
 select sp.sp_id,
         sp.sales_person,
         sp.team,
         sum(sd.amount) as total_sales
  from sales_persons sp
  join sales_data sd
    on sp.sp_id = sd.sp_id
  group by sp.sp_id, sp.sales_person, sp.team
  order by total_sales desc
)
select sp_id,
sales_person,
team,
total_sales,
(case 
when total_sales >= 1800000 then 'high_performers'
when total_sales >= 1600000  then 'medium_performers'
else 'low_performers'
end) as performance_flag
from sales;

-- 2) Find seasonality patterns (which months perform best).
select 
date_format(sale_date,'%m') as months,
sum(amount) as monthly_sales
from sales_data
group by date_format(sale_date,'%m') 
order by monthly_sales desc;

-- 3) Identify customer-region dependency:
 with total_sales as(
select 
sp.sp_id,
sp.sales_person,
g.region,
sum(sd.amount) as total_sales
from sales_data sd 
join sales_persons sp 
on sp.SP_ID = sd.Sp_id
join geography g
on sd.Geo_id = g.Geo_id
group by sp.sp_id,
sp.sales_person,
g.region
order by total_sales desc)
, region_dependency as (
select *,
row_number()over(partition by sp_id order by total_sales desc) as region_rank
from total_sales
)
select * from region_dependency
where region_rank = 1;


-- 4) Which products sell only in certain regions?
select *
from (
  select
    p.product_id,
    p.product,
    count(distinct g.region) as region_count
  from sales_data sd
  join products p on sd.product_id = p.product_id
  join geography g on sd.geo_id = g.geo_id
  group by p.product_id, p.product
) t
where region_count < 3;


--  5) Calculate cumulative revenue over time.
with dialy_revenue as (
select 
sale_date,
sum(amount) as dialy_revenue
from sales_data
group by sale_date
)
select *,
sum(dialy_revenue)over(order by sale_date) as cummilative_revenue
from dialy_revenue;

-- 6*)Detect sales anomalies (transactions unusually high/low).
-- Transactions that are far from the average transaction value
with stats as (
  select 
    avg(amount) as avg_amount,
    stddev(amount) as std_amount 
    # stddev is used to calculate the standard deviation of set of numeric values
    #avg_amount → what’s “normal”
    #std_amount → how much variation is normal
  from sales_data
)
 , flagged_sales as (
  select 
    sd.sale_date,
    sd.sp_id,
    sd.product_id,
    sd.amount,
    st.avg_amount,
    st.std_amount,
    case
      when sd.amount > st.avg_amount + 2 * st.std_amount then 'HIGH_ANOMALY'
      when sd.amount < st.avg_amount - 2 * st.std_amount then 'LOW_ANOMALY'
      else 'NORMAL'
    end as anomaly_flag
  from sales_data sd
  cross join stats st
)
select *
from flagged_sales
where anomaly_flag <> 'NORMAL'
order by amount desc;

-- 7)Compare product size vs profitability.
/* =========================================================
   PRODUCT SIZE vs PROFITABILITY ANALYSIS
   One row per product (correct grain)
   ========================================================= */

WITH product_metrics AS (
    SELECT
        p.product_id,
        p.product,
        
        /* Product size */
        SUM(sd.boxes) AS total_boxes_sold,
        
        /* Revenue */
        SUM(sd.amount) AS total_revenue,
        
        /* Profit */
        SUM(sd.amount - (sd.boxes * p.cost_per_box)) AS total_profit
    FROM sales_data sd
    JOIN products p
        ON sd.product_id = p.product_id
    GROUP BY
        p.product_id,
        p.product
)

SELECT
    product_id,
    product,
    total_boxes_sold,
    total_revenue,
    total_profit,
    
    /* Profitability metric */
    ROUND((total_profit / total_revenue) * 100, 2) AS profit_margin_pct,
    
    /* Product segmentation */
    CASE
        WHEN total_boxes_sold > AVG(total_boxes_sold) OVER ()
         AND total_profit > AVG(total_profit) OVER ()
            THEN 'HIGH_SIZE_HIGH_PROFIT'
            
        WHEN total_boxes_sold > AVG(total_boxes_sold) OVER ()
         AND total_profit <= AVG(total_profit) OVER ()
            THEN 'HIGH_SIZE_LOW_PROFIT'
            
        WHEN total_boxes_sold <= AVG(total_boxes_sold) OVER ()
         AND total_profit > AVG(total_profit) OVER ()
            THEN 'LOW_SIZE_HIGH_PROFIT'
            
        ELSE 'LOW_SIZE_LOW_PROFIT'
    END AS product_segment

FROM product_metrics
ORDER BY total_boxes_sold DESC;

/* 8) Build a KPI summary table:
Total Revenue
Total Profit
Avg Order Value
Best Product
Best Sales Person
*/


WITH base_kpis AS (
    SELECT
        SUM(sd.amount) AS total_revenue,
        SUM(sd.amount - (sd.boxes * p.cost_per_box)) AS total_profit,
        ROUND(AVG(sd.amount), 2) AS avg_order_value
    FROM sales_data sd
    JOIN products p
      ON sd.product_id = p.product_id
),
best_product AS (
    SELECT
        p.product AS best_product
    FROM sales_data sd
    JOIN products p
      ON sd.product_id = p.product_id
    GROUP BY p.product
    ORDER BY SUM(sd.amount) DESC
    LIMIT 1
),
best_sales_person AS (
    SELECT
        sp.sales_person AS best_sales_person
    FROM sales_data sd
    JOIN sales_persons sp
      ON sd.sp_id = sp.sp_id
    GROUP BY sp.sales_person
    ORDER BY SUM(sd.amount) DESC
    LIMIT 1
)

SELECT
    bk.total_revenue,
    bk.total_profit,
    bk.avg_order_value,
    bp.best_product,
    bsp.best_sales_person
FROM base_kpis bk
CROSS JOIN best_product bp
CROSS JOIN best_sales_person bsp;


